// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bulk-id-studio/BulkIdStudio.tsx": () => import("../components/mockups/bulk-id-studio/BulkIdStudio.tsx")
};
